import streamlit as st

st.title("Rohefaktori arvutustabeli juhised")
st.write("Rohefaktori arvutustabel on koostatud selleks, et hõlbustada Tallinna linna planeerimisprotsessis ökoloogiliselt kvaliteetsete rohelahenduste kavandamist. Arvutustabel lihtsustab nõuetekohase arvutuse läbiviimist. Rohefaktori arvutustabel eristab detailplaneeringu ja ehitusprojekti tasandi arvutuse. Arvutuse läbiviimiseks on vajalik määrata alale iseloomulik rohefaktori taotlusväärtus ja kirjeldada kavandatav lahendus, et tõendada vastavust taotlusväärtusele. Täites tabelis vormidel nõutud lahtrid, saab teada rohefaktori arvutuse tulemuse. Kavandatav lahendus täidab rohefaktori nõuded, kui lahenduse arvutatud väärtus vastab taotlusväärtusele. Lisainformatsiooni saamiseks külasta veebilehte: https://www.tallinn.ee/et/ehitus/rohefaktor. Detailplaneeringu protsessis  on arvutusse haaratud vähem rohekomponente. Detailplaneeringu lahendusega tuleb saavutada rohefaktori taotlusväärtus sama juhtotstarbega alale, seejuures määratakse detailplaneeringu lahendusega vajadusel täpsemad rohefaktori taotlusväärtused planeeringulahenduses määratud kruntidele, mis saavad omakorda taotlusväärtuseks ehitusloa protsessis. Taotlusväärtus lähtub planeeringu lähtetingimustes (või üldplaneeringus etteantud rohealade protsendist, maakasutuse tüübist ja sellest kui suur osa olemasolevast hoonestusest rekonstrueeritakse). Ehitusprojektidele rakendub arvutustabel lehel RF-ehitusprojekt, kus on mõnevõrra detailsem rohekomponentide käsitlus. Ehitusprojekti taotlusväärtus tuleb etteantuna detailplaneeringust või nende alade puhul, kus  detailplaneering pole nõutav, arvutatakse sarnaselt detailplaneeringu rohefaktorile lähtuvalt projekteerimistingimustes etteantud rohealade osakaalust, maakasutuse tüübist ja rekonstrueeritavate hoonete mahust. Mõlema arvutuse puhul toetab olemasolevate puittaimede arvestamist mudelis arvutustabel lehel Puittaimede sisestusmoodul. See võimaldab sisestada haljastuse inventeerimise käigus kaardistatud puittaimede informatsiooni, mis võetakse arvesse rohefaktori arvutuses (nii detailplaneeringu rohefaktori kui ehitusprojektide rohefaktori tarbeks).")
st.divider()

st.write("**Detailplaneeringu** protsessis  on arvutusse haaratud vähem rohekomponente. Detailplaneeringu lahendusega tuleb saavutada rohefaktori taotlusväärtus sama juhtotstarbega alale, seejuures määratakse detailplaneeringu lahendusega vajadusel täpsemad rohefaktori taotlusväärtused planeeringulahenduses määratud kruntidele, mis saavad omakorda taotlusväärtuseks ehitusloa protsessis. Taotlusväärtus lähtub planeeringu lähtetingimustes (või üldplaneeringus etteantud rohealade protsendist, maakasutuse tüübist ja sellest kui suur osa olemasolevast hoonestusest rekonstrueeritakse).")
#st.divider()
st.write("**Ehitusprojektidele** rakendub arvutustabel lehel RF-ehitusprojekt, kus on mõnevõrra detailsem rohekomponentide käsitlus. Ehitusprojekti taotlusväärtus tuleb etteantuna detailplaneeringust või nende alade puhul, kus  detailplaneering pole nõutav, arvutatakse sarnaselt detailplaneeringu rohefaktorile lähtuvalt projekteerimistingimustes etteantud rohealade osakaalust, maakasutuse tüübist ja rekonstrueeritavate hoonete mahust.")
#st.divider()
st.write("Mõlema arvutuse puhul toetab olemasolevate puittaimede arvestamist mudelis arvutustabel lehel Puittaimede sisestusmoodul. See võimaldab sisestada haljastuse inventeerimise käigus kaardistatud puittaimede informatsiooni, mis võetakse arvesse rohefaktori arvutuses (nii detailplaneeringu rohefaktori kui ehitusprojektide rohefaktori tarbeks).")
st.header("Taotlusväärtuse sisestamine")
st.write("""
Esimese sammuna kirjeldatakse Taotlusväärtuse sisendid töölehel planeeritav ala rohefaktor taotlusväärtuse määramise tarbeks. Sisestatakse ala pindala, määratakse rekonstrueeritavate hoonete pindala (vähendab taotlusväärtust), peamine maakasutus ning ette antud (planeeringu lähtetingimustes, üldplaneeringus või projekteerimistingimustes) rohealade protsent (suurendab taotlusväärtust).
         
- **TV** = HOK + RKK - SHK
- **TV** – taotlusväärtus  
- **HOK** – ÜP haljastuse osakaalu komponent  
- **RKK** – Rohealade kvaliteedi komponent (juhtotstarbest lähtuv rohetaristu kvaliteedinõue)  
- **SHK** – Säilitatavate hoonete komponent (hoone aluse pinna arvelt vähendatud RKK)  

**Info sisestatakse arvutustabelisse rohelistesse lahtritesse**""")

st.write("Ehitusprojekti taseme rohefaktori taotlusväärtus tuleb enamasti etteantuna detailplaneeringust ning kannab seeläbi kontrollfunktsiooni, et planeeringulahenduses kavandatud rohetaristu realiseeritakse lubatud kvaliteedis. Alade puhul, kus detailplaneering pole nõutav, arvutatakse taotlusväärtus sarnaselt detailplaneeringu rohefaktorile lähtuvalt projekteerimistingimustes etteantud rohealade osakaalust, maakasutuse tüübist ja krundil säilitatavate/rekonstrueeritavate hoonete mahust")

st.header("Rohefaktori arvutus")

st.write("Suure tõenäosusega ei näe planeeringulahendus ette kõiki rohefaktori arvutustabelis pakutud komponente. Tabelisse tuleb märkida ainult nende alade pindala, mida lahendus ette näeb. Erinevad rohetaristu elemendid on tabelis erinevate kaalumiskoefitsientidega. Eristatakse põhifaktoreid ja boonusfaktoreid. Põhifaktoritest lähtuv rohefaktor arvutatakse maakattetüüpidest lähtuvalt, boonusfaktoritega saab lahendusi mitmekesistada. See tähendab, et boonusfaktorid rakenduvad juba põhifaktoritega kaalutud aladele (va. väärtuslikud elupaigad, kus see pole lubatud). Juhul kui detailplaneeringus kavandatud maakasutus ei võimalda rohefaktori taotlusväärtuses nõutud ökoloogilist kvaliteeti saavutada, on vajalik leida lahendus kuidas lahendusse integreerida täiendavaid roheelemente, mis nõutud kvaliteeti tõstaks. Erinevate boonusfaktorite rakendamist tuleb planeeringu seletuskirjas selgitada, andes seejuures nõuded projekti faasis täpsemale käsitlusele.")

st.write("Haljastuse mitmekesisuse moodulis saab võtta arvesse säilitatavate puude ja kavandatava haljastuse mitmekesisust. Säilitatavate puude arvesse võtmine käib dendroloogilise hinnangu alusel. Puud sisestatakse eraldi töölehel. Rajatava haljastuse puhul tuleb planeeringulahenduses näidata ja seletuskirjas selgitada, kuidas lahendus tulevikus realiseeritakse")

st.write("Võrreldes detailplaneeringu rohefaktoriga on ehitusprojekti rohefaktoris mõnevõrra rohkem erinevaid ökoloogilisi komponente - elupaiku ja rohetaristu lahendusi, mida arvutusse kaasata. Juhul kui ehitusprojekt koostatakse detailplaneeringu alusel, tuleb ehitusprojekti staadiumis võtta detailplaneeringu rohefaktori arvutus ja seda täpsustada. Lahenduse oluline muutus peab olema seletuskirjas selgelt põhjendatud.")